configure spring boot, added Book entity with service  and repository…
Nonzeq/Online-Book-store pull request #1
Opened 2024-03-12 14:16 UTC by Nonzeq

… implementation

2024-03-12 18:18 UTC, MentorMA requested changes

2024-03-12 18:18 UTC, MentorMA commented on src/main/java/com/kobylchak/bookstore/repository/BookRepositoryImpl.java
> +    }
Lets use lombok instad of this approach

2024-03-12 18:18 UTC, MentorMA commented on src/main/java/com/kobylchak/bookstore/repository/BookRepositoryImpl.java
> +    }
@requiredArgsConstructor

2024-03-13 13:33 UTC, Rommelua requested changes

2024-03-13 13:33 UTC, Rommelua commented on src/main/java/com/kobylchak/bookstore/BookStoreApplication.java
> +    private BookService bookService;
Lets use lombok for constructor creating
```suggestion
    private BookService bookService;
```

2024-03-13 13:33 UTC, Rommelua commented on src/main/java/com/kobylchak/bookstore/model/Book.java
> +@Data
do not use Data with entity classes

2024-03-13 17:48 UTC, closed without merging