spring-security-hw
Nonzeq/Online-Book-store pull request #10
Opened 2024-03-30 13:06 UTC by Nonzeq

2024-03-30 16:53 UTC, okuzan requested changes

2024-03-30 16:53 UTC, okuzan commented on src/main/java/com/kobylchak/bookstore/controller/AuthenticationController.java
> +
```suggestion
```

2024-03-30 16:53 UTC, okuzan commented on src/main/java/com/kobylchak/bookstore/mapper/UserMapper.java
> +
```suggestion
```

2024-03-30 16:53 UTC, okuzan commented on src/main/resources/db/changelog/changes/08-insert-user_roles-table.yml
> +                  value: 1
don't forget to leave last line empty
![image](https://github.com/Nonzeq/Online-Book-store/assets/49767049/ac3dfd8b-2d4e-46b6-9af3-8499e4ece139)

2024-03-30 16:53 UTC, okuzan commented on src/main/resources/db/changelog/changes/06-insert-roles-into-roles-table.yml
> +                  value: ADMIN
```suggestion
                  value: ADMIN

```

2024-03-30 16:53 UTC, okuzan commented on src/main/resources/db/changelog/changes/04-create-role-table.yml
> +                    nullable: false
```suggestion
                    nullable: false

```

2024-03-30 16:53 UTC, okuzan commented on src/main/resources/db/changelog/changes/05-create-user_roles-table.yml
> +                  type: bigint
```suggestion
                  type: bigint

```

2024-03-30 16:53 UTC, okuzan commented on src/main/java/com/kobylchak/bookstore/model/User.java
> +public class User implements UserDetails {
I believe user should implement soft delete at this point

2024-03-31 14:37 UTC, Rommelua requested changes

2024-03-31 14:37 UTC, Rommelua commented on src/main/java/com/kobylchak/bookstore/service/user/RegistrationServiceImpl.java
> +    public List<UserResponseDto> getAll() {
Why do we need this method? Delete it.

2024-03-31 14:37 UTC, Rommelua commented on src/main/java/com/kobylchak/bookstore/service/user/RegistrationService.java
> +    List<UserResponseDto> getAll();
Why do we need this method? Delete it.

2024-03-31 14:37 UTC, Rommelua commented on src/main/java/com/kobylchak/bookstore/dto/user/UserResponseDto.java
> +    private Set<Long> roles;
We do not need this field here

2024-04-01 11:31 UTC, Rommelua requested changes

2024-04-01 11:31 UTC, Rommelua commented on src/main/java/com/kobylchak/bookstore/repository/user/UserRepository.java
> +    List<User> findAllUsers();
This method is not used - delete it

2024-04-01 14:34 UTC, MAMentorFX approved these changes

2024-04-01 14:34 UTC, MAMentorFX commented on src/main/java/com/kobylchak/bookstore/model/User.java
> +@SQLDelete(sql = "UPDATE users set is_deleted = true WHERE id=?")
```suggestion
@SQLRestriction("is_delete = FALSE")
@SQLDelete(sql = "UPDATE users SET is_deleted = TRUE WHERE id = ?")
```

2024-04-01 14:34 UTC, MAMentorFX commented on src/main/java/com/kobylchak/bookstore/repository/user/UserRepository.java
> +    @Query("from User u join fetch u.roles where u.email = :email")
```suggestion
    @Query("FROM User u JOIN FETCH u.roles WHERE u.email = :email")
```

2024-04-01 15:00 UTC, MAMentorFX commented on src/main/java/com/kobylchak/bookstore/service/user/RegistrationServiceImpl.java
>      public UserResponseDto register(UserRegistrationRequestDto requestDto)
```suggestion
@Transactional
    public UserResponseDto register(UserRegistrationRequestDto requestDto)
```

2024-04-01 15:15 UTC, merged