spring-boot-prac-shoppingCart
Nonzeq/Online-Book-store pull request #13
Opened 2024-04-06 14:50 UTC by Nonzeq

2024-04-07 10:42 UTC, MAMentorFX requested changes

2024-04-07 10:42 UTC, MAMentorFX commented on src/main/java/com/kobylchak/bookstore/mapper/CartItemMapper.java
> +
```suggestion
```

2024-04-07 10:42 UTC, MAMentorFX commented on src/main/java/com/kobylchak/bookstore/service/cart/ShoppingCartServiceImpl.java
> +        String email = SecurityContextHolder.getContext().getAuthentication().getName();
You shouldn't use Infrastructure code here, you shoud pass Authentication to each controller's method, and pass user (retrieved from aunthetication) to service

2024-04-07 10:42 UTC, MAMentorFX commented on src/main/java/com/kobylchak/bookstore/service/cart/ShoppingCartServiceImpl.java
> +    }
Why are those Transactional, you put trasactional if class has more than one call to DB

2024-04-07 10:42 UTC, MAMentorFX commented on src/main/java/com/kobylchak/bookstore/service/cart/item/CartItemServiceImpl.java
> +    public ShoppingCart updateItem(
```suggestion
@Transactional
    public ShoppingCart updateItem(
```

2024-04-08 08:27 UTC, Vasul-Pankiv approved these changes

2024-04-08 08:34 UTC, merged